### ISSUE TITLE
Inputs don't resize on height

### ISSUE THREAD

**Issue by chasturansky** [denali-design/denali-site#115]
<img width="550" alt="Screen Shot 2020-04-07 at 9 37 36 AM" src="https://user-images.githubusercontent.com/15337851/81113988-fb172e00-8ed5-11ea-8254-10f2962b9a9d.png">

**Comment by marcosand** [comment]
@chasturansky Do we allow resizing on other inputs? (Calendar Input for example)
<img width="348" alt="Screen Shot 2020-07-07 at 9 40 46 AM" src="https://user-images.githubusercontent.com/58989034/86814235-f8e86180-c035-11ea-8ca5-cba7cd2a441a.png">
Or do we just want this freedom for all elements in the Fields submenu?

**Comment by chasturansky** [comment]
I think they should be like the new buttons since we allow them to resize. Fewer complexities for us.
