### ISSUE TITLE
Calendar Fields

### ISSUE THREAD

**Issue by marcosand** [denali-design/denali-site#125]
<img width="439" alt="Screen Shot 2020-07-07 at 9 43 04 AM" src="https://user-images.githubusercontent.com/58989034/86814464-4fee3680-c036-11ea-88e1-cb6ef4a7be37.png">

**Comment by chasturansky** [comment]
- [ ] Resize Issues
- [ ] Fonts not installed?

**Comment by chasturansky** [comment]
<img width="434" alt="Screen Shot 2020-07-31 at 10 37 16 AM" src="https://user-images.githubusercontent.com/15337851/89204534-1e03bd80-d56b-11ea-94ee-a398705ea47f.png">
Can we set a default?
