### ISSUE TITLE
A TYPO in the footer

### ISSUE THREAD

**Issue by Deep310** [denali-design/denali-site#142]
Hi! I was checking out this website for the first time and I noticed a typo in the footer on your website.

Apparently, it says "Make a component suggestion on out Github page". Instead of "out", it should be "our" Github page. 

I checked your source code. I looked into **_denali-site/_includes/footer.html_** and on line 21, I see that it is "our" so typo isn't there. It's just on website. 

I don't know if that's the source code for footer. I'm just a beginner in open source world but noticed it and am reporting it. 

![Screenshot_2020-09-30 Denali Designer Developer Tools(1)](https://user-images.githubusercontent.com/55121371/94694494-e9aa4480-0302-11eb-8562-9047c7766bb3.png)

**Comment by jkusa** [comment]
Thanks for filing an issue @Deep310 🙏

**Comment by Deep310** [comment]
Glad I could contribute! @jkusa
